import FormData from "../components/registerAccount";

const people: FormData[] = [
    {
        firstName: 'Alice',
        age: '28',
        city: 'Stockholm',
        gender: 'Female',
        sexualOrientation: 'Heterosexual',
        religion: 'Atheist',
        interests: ['Läsa', 'Resor', 'Yoga', 'Fotografi', 'Teater'],
        hasChildren: false,
        wantsChildren: true,
        smokes: 'No',
        relationshipStatus: 'friends',
        education: 'University',
        photo: null,
        favoriteSong: 'Bohemian Rhapsody',
        favoriteMovie: 'Inception',
        email: 'alice@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan mina vänner.',
        lifeStatement2: 'Jag blir mest inspirerad när jag är i naturen.'
    },
    {
        firstName: 'Bob',
        age: '34',
        city: 'Göteborg',
        gender: 'Male',
        sexualOrientation: 'Heterosexual',
        religion: 'Christian',
        interests: ['Fotboll', 'Spel', 'Träning', 'Teknik', 'Bilar'],
        hasChildren: true,
        wantsChildren: false,
        smokes: 'Yes',
        relationshipStatus: 'serious',
        education: 'Bachelor’s degree',
        photo: null,
        favoriteSong: 'Highway to Hell',
        favoriteMovie: 'The Dark Knight',
        email: 'bob@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min familj.',
        lifeStatement2: 'Jag blir mest inspirerad när jag ser framsteg.'
    },
    {
        firstName: 'Carla',
        age: '26',
        city: 'Malmö',
        gender: 'Female',
        sexualOrientation: 'Homosexual',
        religion: 'Jewish',
        interests: ['Matlagning', 'Vin', 'Hundar', 'Baka', 'Politik'],
        hasChildren: false,
        wantsChildren: false,
        smokes: 'No',
        relationshipStatus: 'casual',
        education: 'Master’s degree',
        photo: null,
        favoriteSong: 'Rolling in the Deep',
        favoriteMovie: 'The Shawshank Redemption',
        email: 'carla@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min kreativitet.',
        lifeStatement2: 'Jag blir mest inspirerad när jag lär mig nya saker.'
    },
    {
        firstName: 'David',
        age: '40',
        city: 'Uppsala',
        gender: 'Male',
        sexualOrientation: 'Heterosexual',
        religion: 'Atheist',
        interests: ['Bilar', 'Filosofi', 'Historia', 'Vin', 'Målning'],
        hasChildren: true,
        wantsChildren: false,
        smokes: 'No',
        relationshipStatus: 'casual',
        education: 'High school',
        photo: null,
        favoriteSong: 'Imagine',
        favoriteMovie: 'Gladiator',
        email: 'david@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan mina böcker.',
        lifeStatement2: 'Jag blir mest inspirerad när jag diskuterar djupa ämnen.'
    },
    {
        firstName: 'Emma',
        age: '22',
        city: 'Örebro',
        gender: 'Female',
        sexualOrientation: 'Bisexual',
        religion: 'Muslim',
        interests: ['Mat', 'Sociala aktiviteter', 'Yoga', 'Vänner', 'Podcast'],
        hasChildren: false,
        wantsChildren: true,
        smokes: 'No',
        relationshipStatus: 'casual',
        education: 'High school',
        photo: null,
        favoriteSong: 'Shake It Off',
        favoriteMovie: 'The Hunger Games',
        email: 'emma@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min familj.',
        lifeStatement2: 'Jag blir mest inspirerad när jag hjälper andra.'
    },
    {
        firstName: 'John',
        age: '29',
        city: 'Lund',
        gender: 'Male',
        sexualOrientation: 'Heterosexual',
        religion: 'None',
        interests: ['Fotboll', 'Basket', 'Spel', 'Resor', 'Träning'],
        hasChildren: false,
        wantsChildren: false,
        smokes: 'No',
        relationshipStatus: 'single',
        education: 'Bachelor’s degree',
        photo: null,
        favoriteSong: 'Lose Yourself',
        favoriteMovie: 'The Matrix',
        email: 'john@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan mina vänner.',
        lifeStatement2: 'Jag blir mest inspirerad när jag ser framgång.'
    },
    {
        firstName: 'Sophia',
        age: '31',
        city: 'Göteborg',
        gender: 'Female',
        sexualOrientation: 'Heterosexual',
        religion: 'Christian',
        interests: ['Matlagning', 'Yoga', 'Vänner', 'Podcast', 'Baka'],
        hasChildren: true,
        wantsChildren: true,
        smokes: 'No',
        relationshipStatus: 'married',
        education: 'Master’s degree',
        photo: null,
        favoriteSong: 'Halo',
        favoriteMovie: 'Titanic',
        email: 'sophia@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min familj.',
        lifeStatement2: 'Jag blir mest inspirerad när jag hör inspirerande berättelser.'
    },
    {
        firstName: 'Peter',
        age: '38',
        city: 'Stockholm',
        gender: 'Male',
        sexualOrientation: 'Homosexual',
        religion: 'Atheist',
        interests: ['Bilar', 'Teknik', 'Vin', 'Natur', 'Historia'],
        hasChildren: true,
        wantsChildren: false,
        smokes: 'Yes',
        relationshipStatus: 'single',
        education: 'University',
        photo: null,
        favoriteSong: 'What a Wonderful World',
        favoriteMovie: 'The Godfather',
        email: 'peter@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan mina erfarenheter.',
        lifeStatement2: 'Jag blir mest inspirerad när jag ser människor växa.'
    },
    {
        firstName: 'Olivia',
        age: '25',
        city: 'Malmö',
        gender: 'Female',
        sexualOrientation: 'Heterosexual',
        religion: 'None',
        interests: ['Filosofi', 'Mat', 'Vänner', 'Resor', 'Sociala aktiviteter'],
        hasChildren: false,
        wantsChildren: false,
        smokes: 'No',
        relationshipStatus: 'in a relationship',
        education: 'Bachelor’s degree',
        photo: null,
        favoriteSong: 'Blinding Lights',
        favoriteMovie: 'The Notebook',
        email: 'olivia@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min nyfikenhet.',
        lifeStatement2: 'Jag blir mest inspirerad när jag reflekterar över livet.'
    },
    {
        firstName: 'Max',
        age: '33',
        city: 'Västerås',
        gender: 'Male',
        sexualOrientation: 'Heterosexual',
        religion: 'Muslim',
        interests: ['Teknik', 'Historia', 'Fotboll', 'Bilar', 'Politik'],
        hasChildren: true,
        wantsChildren: true,
        smokes: 'No',
        relationshipStatus: 'married',
        education: 'High school',
        photo: null,
        favoriteSong: 'Shape of You',
        favoriteMovie: 'Inception',
        email: 'max@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan mina drömmar.',
        lifeStatement2: 'Jag blir mest inspirerad när jag ser människor uppnå sina mål.'
    },
    {
        firstName: 'Laura',
        age: '24',
        city: 'Uppsala',
        gender: 'Female',
        sexualOrientation: 'Bisexual',
        religion: 'Atheist',
        interests: ['Resor', 'Yoga', 'Djur', 'Teater', 'Fotografi'],
        hasChildren: false,
        wantsChildren: true,
        smokes: 'No',
        relationshipStatus: 'single',
        education: 'University',
        photo: null,
        favoriteSong: 'Someone Like You',
        favoriteMovie: 'La La Land',
        email: 'laura@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min passion för konst.',
        lifeStatement2: 'Jag blir mest inspirerad när jag är ute i naturen.'
    },
    {
        firstName: 'Liam',
        age: '27',
        city: 'Stockholm',
        gender: 'Male',
        sexualOrientation: 'Heterosexual',
        religion: 'Christian',
        interests: ['Träning', 'Spel', 'Teknik', 'Politik', 'Bilar'],
        hasChildren: false,
        wantsChildren: false,
        smokes: 'Yes',
        relationshipStatus: 'single',
        education: 'Bachelor’s degree',
        photo: null,
        favoriteSong: 'Thunderstruck',
        favoriteMovie: 'The Dark Knight',
        email: 'liam@email.com',
        lifeStatement1: 'Jag skulle aldrig kunna leva utan min frihet.',
        lifeStatement2: 'Jag blir mest inspirerad när jag ser människor kämpa för sina mål.'
    }
];

export default people;
